import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const getRubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ezhil portfolio",
  description: "Generated by create next app",
  keywords:["react", "server components","next js","ezhil portfolio","portfolio","trending portfolio"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getRubik.variable} ${geistMono.variable} ${geistSans.variable}  antialiased `}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
